/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 alcan.gltf 
Author: LiliumLetifer (https://sketchfab.com/LiliumLetifer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/food-cans-3d669bd31c944260b2c2dae52c200c39
Title: Food Cans
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Alcan(props) {
  const { nodes, materials } = useGLTF("/alcan.gltf");
  return (
    <group {...props} dispose={null}>
      <group rotation={[0, 1.542, -Math.PI]} scale={0.001}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[460.754, -213.525, 77.461]}
            rotation={[-Math.PI, 0, Math.PI]}
            scale={[-50.423, 50.423, 70.644]}
          >
            <mesh
              geometry={nodes.defaultMaterial_1.geometry}
              material={materials.material_4}
            />
            <mesh
              geometry={nodes.defaultMaterial_2.geometry}
              material={materials.material_4}
            />
          </group>
          <group
            position={[520.804, -126.894, 48.949]}
            rotation={[0, 0, 2.204]}
            scale={44.499}
          >
            <mesh
              geometry={nodes.defaultMaterial_5.geometry}
              material={materials.material_1}
            />
            <mesh
              geometry={nodes.defaultMaterial_6.geometry}
              material={materials.material_1}
            />
          </group>
          <group
            position={[405.636, -298.366, 62.528]}
            rotation={[0, 0, 0.677]}
            scale={[39.727, 39.727, 57.215]}
          >
            <mesh
              geometry={nodes.defaultMaterial_7.geometry}
              material={materials.material}
            />
            <mesh
              geometry={nodes.defaultMaterial_8.geometry}
              material={materials.material}
            />
          </group>
          <mesh
            geometry={nodes.defaultMaterial.geometry}
            material={materials.material_5}
            position={[580.242, -294.175, 33.409]}
            rotation={[-0.023, -0.056, -1.953]}
            scale={[11.039, 18.051, 7.769]}
          />
          <mesh
            geometry={nodes.defaultMaterial_3.geometry}
            material={materials.material_3}
            position={[572.32, -215.287, 27.079]}
            scale={[47.414, 47.414, 22.669]}
          />
          <mesh
            geometry={nodes.defaultMaterial_4.geometry}
            material={materials.material_2}
            position={[502.148, -314.707, 19.092]}
            scale={[47.053, 47.053, 15.883]}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/alcan.gltf");
