/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 ls.gltf 
Author: neeb17 (https://sketchfab.com/neeb17)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lipstick-db40146676ce4320968e532517d43f3c
Title: Lipstick
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/ls.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_4.geometry}
        material={materials.Black_Gloss}
        position={[-3.014, 0.467, 0]}
        rotation={[0, 0, -1.565]}
      />
      <mesh
        geometry={nodes.Object_6.geometry}
        material={materials.Black_Gloss}
        position={[-0.823, 0.547, -0.717]}
        rotation={[0.02, 0.383, -1.625]}
      />
      <mesh
        geometry={nodes.Object_8.geometry}
        material={materials["Gold_Gloss.001"]}
        position={[-3.014, 0.467, 0]}
        rotation={[0, 0, -1.565]}
      />
      <mesh
        geometry={nodes.Object_10.geometry}
        material={materials.Gold_Gloss}
        position={[-3.014, 0.467, 0]}
        rotation={[0, 0, -1.565]}
      />
      <mesh
        geometry={nodes.Object_12.geometry}
        material={materials.Paint}
        position={[-1.543, 0.476, 0]}
        rotation={[-0.71, 0, -1.565]}
      />
    </group>
  );
}

useGLTF.preload("/ls.gltf");
