import type { TeamMember } from "@/types/teams";

export const teamMembers: TeamMember[] = [
  // Admin team
  {
    firstName: "William",
    lastName: "Wang",
    team: "Admin",
    tag: "Founder",
    image: "/teamAvatars/william wang.webp",
    pronouns: "",
    links: ["https://www.linkedin.com/in/williamuw/"],
    quote: "55x hackathon winner, karaoke enthusiast!",
  },
  {
    firstName: "James",
    image: "/teamAvatars/james c.webp",
    team: "Admin",
    tag: "Admin Member",
    links: ["https://example.com/james"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Jerry",
    image: "/teamAvatars/jerry zhu.webp",
    team: "Admin",
    tag: "Admin Member",
    links: ["https://example.com/jerry"],
    quote: "Placeholder quote",
  },

  // Mentor team
  {
    firstName: "Nausher",
    team: "Mentor",
    tag: "Mentor",
    links: ["https://example.com/nausher"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Arnnav",
    image: "/teamAvatars/arnnav kudale.webp",
    team: "Mentor",
    tag: "Mentor",
    links: ["https://example.com/arnnav"],
    quote: "Placeholder quote",
  },

  // Tech team
  {
    firstName: "Jason",
    lastName: "Cameron",
    image: "/teamAvatars/jason cameron.webp",
    team: "Tech",
    tag: "Tech Lead",
    links: [
      "https://www.linkedin.com/in/jsoncameron/",
      "https://github.com/jasonLovesDoggo",
    ],
    quote: "Sleep is for the week",
  },
  {
    firstName: "Araf",
    lastName: "A Alam",
    image: "/teamAvatars/araf a a.webp",
    team: "Tech",
    tag: "Project Manager",
    links: ["https://www.linkedin.com/in/arafa821/"],
    quote: "Code like crazy!",
  },
  {
    firstName: "Chirag",
    pronouns: "he/him",
    image: "/teamAvatars/chirag.webp",
    team: "Tech",
    tag: "Senior Div Centerer",
    links: ["https://github.com/ChiragDalmia/"],
    quote: "I made this landing page ;)",
  },
  {
    firstName: "Sohel",
    // image: "/teamAvatars/sohel.webp",
    team: "Tech",
    tag: "Tech Member",
    links: ["https://example.com/sohel"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Aayan",
    // image: "/teamAvatars/aayan.webp",
    team: "Tech",
    tag: "Tech Member",
    links: ["https://example.com/aayan"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Aiden",
    // image: "/teamAvatars/aiden.webp",
    team: "Tech",
    tag: "Tech Member",
    links: ["https://example.com/aiden"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Joudat",
    image: "/teamAvatars/joudat.webp",
    team: "Tech",
    tag: "Tech Member",
    links: ["https://example.com/joudat"],
    quote: "Placeholder quote",
  },
  {
    firstName: "James",
    image: "/teamAvatars/james liang.webp",
    team: "Tech",
    tag: "Tech Member",
    links: ["https://example.com/james_l"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Fiona",
    image: "/teamAvatars/fiona cai.webp",
    team: "Tech",
    tag: "Tech Member",
    links: ["https://example.com/fiona"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Edem",
    // image: "/teamAvatars/edem.webp",
    team: "Tech",
    tag: "Tech Member",
    links: ["https://example.com/edem"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Aryan",
    // image: "/teamAvatars/aryan.webp",
    team: "Tech",
    tag: "Tech Member",
    links: ["https://example.com/aryan"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Wahib",
    image: "/teamAvatars/wahib barqawi.webp",
    team: "Tech",
    tag: "Tech Member",
    links: ["https://example.com/wahib"],
    quote: "Placeholder quote",
  },

  // Design team
  {
    firstName: "Jess",
    image: "/teamAvatars/jess.webp",
    team: "Design",
    tag: "Design Lead",
    links: ["https://example.com/jess"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Julia",
    image: "/teamAvatars/julia wu.webp",
    team: "Design",
    tag: "Design Member",
    links: ["https://example.com/julia"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Tina",
    // image: "/teamAvatars/tina.webp",
    team: "Design",
    tag: "Design Member",
    links: ["https://example.com/tina"],
    quote: "Placeholder quote",
  },

  // Outreach team
  {
    firstName: "Nirek",
    // image: "/teamAvatars/nirek.webp",
    team: "Outreach",
    tag: "Outreach Lead",
    links: ["https://example.com/nirek"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Jad",
    // image: "/teamAvatars/jad.webp",
    team: "Outreach",
    tag: "Outreach Member",
    links: ["https://example.com/jad"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Ray",
    lastName: "Tan",
    // image: "/teamAvatars/greg.webp",
    team: "Outreach",
    tag: "Outreach Officer",
    links: ["https://www.linkedin.com/in/ray-tan-054ab4228/"],
    quote: "I am Ray Tan of Canada",
  },
  {
    firstName: "Tom",
    image: "/teamAvatars/uday khanna.webp",
    team: "Outreach",
    tag: "Outreach Member",
    links: ["https://example.com/tom"],
    quote: "Placeholder quote",
  },

  // Finance team
  {
    firstName: "Uday",
    lastName: "Khanna",
    // image: "/teamAvatars/uday.webp",
    team: "Finance",
    tag: "Finance Lead",
    links: ["https://www.linkedin.com/in/udaykhanna25/"],
    quote: '"There is No Tomorrow!" - Apollo Creed (Rocky III)',
  },
  // {
  //   firstName: "Derek",
  //   // image: "/teamAvatars/derek.webp",
  //   team: "Finance",
  //   tag: "Finance Member",
  //   links: ["https://example.com/derek"],
  //   quote: "Placeholder quote",
  // },
  // {
  //   firstName: "Shayaan",
  //   // image: "/teamAvatars/shayaan.webp",
  //   team: "Finance",
  //   tag: "Finance Member",
  //   links: ["https://example.com/shayaan"],
  //   quote: "Placeholder quote",
  // },
  {
    firstName: "Sardaul",
    // image: "/teamAvatars/sardaul.webp",
    team: "Finance",
    tag: "Finance Member",
    links: ["https://example.com/sardaul"],
    quote: "Placeholder quote",
  },

  // Logistics team
  {
    firstName: "Aayan",
    // image: "/teamAvatars/aayan_l.webp",
    team: "Logistics",
    tag: "Logistics Lead",
    links: ["https://example.com/aayan_l"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Emilo",
    // image: "/teamAvatars/emilo.webp",
    team: "Logistics",
    tag: "Logistics Lead",
    links: ["https://example.com/emilo"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Jia",
    image: "/teamAvatars/jia.webp",
    team: "Logistics",
    tag: "Logistics Member",
    links: ["https://example.com/jia"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Yang",
    // image: "/teamAvatars/yang.webp",
    team: "Logistics",
    tag: "Logistics Member",
    links: ["https://example.com/yang"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Arnav",
    // image: "/teamAvatars/arnav.webp",
    team: "Logistics",
    tag: "Logistics Member",
    links: ["https://example.com/arnav"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Advaith",
    // image: "/teamAvatars/advaith.webp",
    team: "Logistics",
    tag: "Logistics Member",
    links: ["https://example.com/advaith"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Edward",
    // image: "/teamAvatars/edward.webp",
    team: "Logistics",
    tag: "Logistics Member",
    links: ["https://example.com/edward"],
    quote: "Placeholder quote",
  },

  // Marketing team
  {
    firstName: "Chelsea",
    lastName: "Wong",
    // image: "/teamAvatars/chelsea.webp",
    team: "Marketing",
    tag: "Head of Marketing",
    pronouns: "she/her",
    links: ["https://www.linkedin.com/in/chelseawong07/"],
    quote: "stan enhypen",
  },
  {
    firstName: "Ev",
    // image: "/teamAvatars/ev.webp",
    team: "Marketing",
    tag: "Marketing Lead",
    links: ["https://example.com/ev"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Yashas",
    // image: "/teamAvatars/yashas.webp",
    team: "Marketing",
    tag: "Marketing Lead",
    links: ["https://example.com/yashas"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Naman",
    // image: "/teamAvatars/naman.webp",
    team: "Marketing",
    tag: "Marketing Member",
    links: ["https://example.com/naman"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Anushka",
    // image: "/teamAvatars/anushka.webp",
    team: "Marketing",
    tag: "Marketing Member",
    links: ["https://example.com/anushka"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Claire",
    lastName: "L",
    team: "Marketing",
    tag: "Marketing Member",
    links: ["https://example.com/claire"],
    quote: "Placeholder quote",
  },
];
