import type { TeamMember } from "@/types/teams";

export const teamMembers: TeamMember[] = [
  // Admin team
  {
    firstName: "William",
    lastName: "Wang",
    team: "Admin",
    tag: "Founder",
    image: "/teamAvatars/william-wang.webp",
    pronouns: "",
    links: ["https://www.linkedin.com/in/williamuw/"],
    quote: "55x hackathon winner, karaoke enthusiast!",
  },
  {
    firstName: "James",
    lastName: "Cao",
    image: "/teamAvatars/james-c.webp",
    team: "Admin",
    tag: "Admin Member",
    pronouns: "he/him",
    links: ["https://www.instagram.com/hackathoncanada/"],
    quote: "asta vista baby",
  },
  {
    firstName: "Jerry",
    lastName: "Zhu",
    image: "/teamAvatars/jerry-zhu.webp",
    team: "Admin",
    tag: "Admin Member",
    pronouns: "he/him",
    links: ["https://instagram.com/jerry.cyz"],
    quote: "I love ABGs",
  },

  // Mentor team
  {
    firstName: "Nausher",
    team: "Mentor",
    tag: "Mentor",
    links: ["https://example.com/nausher"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Arnav",
    lastName: "Chauhan",
    pronouns: "he/him",
    image: "/teamAvatars/arnav-chauhan.webp",
    team: "Mentor",
    tag: "Advisor",
    links: ["https://www.linkedin.com/in/arnavchauhan/"],
    quote: "Nothing Changes, If Nothing Changes",
  },

  // Tech team
  {
    firstName: "Jason",
    lastName: "Cameron",
    image: "/teamAvatars/jason.webp",
    team: "Tech",
    tag: "Tech Lead",
    links: [
      "https://www.linkedin.com/in/jsoncameron/",
      "https://github.com/jasonLovesDoggo",
    ],
    quote: "Sleep is for the week",
  },
  {
    firstName: "Araf",
    lastName: "A",
    image: "/teamAvatars/araf.webp",
    team: "Tech",
    tag: "Project Manager",
    links: ["https://www.linkedin.com/in/arafa821/"],
    quote: "Code like crazy!",
  },
  {
    firstName: "Chirag",
    pronouns: "he/him",
    image: "/teamAvatars/chirag.webp",
    team: "Tech",
    tag: "Senior Div Centerer",
    links: ["https://github.com/ChiragDalmia/"],
    quote: "I made this landing page ;)",
  },
  {
    firstName: "Aayan",
    lastName: "Karmali",
    image: "/teamAvatars/aayan-karmali.webp",
    team: "Tech",
    tag: "Hack Canada [Backend]",
    pronouns: "he/him",
    links: ["https://www.linkedin.com/in/aayan-karmali/"],
    quote: "Minecraft, Python, and Netflix enthusiast :)",
  },
  // TODO: May be removed
  // {
  //   firstName: "Aiden",
  //   // image: "/teamAvatars/aiden.webp",
  //   team: "Tech",
  //   tag: "Tech Member",
  //   links: ["https://example.com/aiden"],
  //   quote: "Placeholder quote",
  // },
  {
    firstName: "Joudat",
    lastName: "Haroon",
    image: "/teamAvatars/joudat.webp",
    team: "Tech",
    tag: "Tech Member",
    pronouns: "he/him",
    links: ["https://www.linkedin.com/in/joudat-haroon/"],
    quote: "arch-wizard",
  },
  {
    firstName: "James",
    lastName: "Liang",
    image: "/teamAvatars/james-l.webp",
    team: "Tech",
    tag: "Tech Member",
    links: ["https://www.linkedin.com/in/james-liang-/"],
    quote: "uwu",
  },
  {
    firstName: "Fiona",
    lastName: "Cai",
    image: "/teamAvatars/fiona.webp",
    team: "Tech",
    tag: "Frontend Developer",
    links: ["http://linkedin.com/in/fiona--cai"],
    quote: "I like matcha very mucha",
  },
  // {
  //   firstName: "Edem",
  //   // image: "/teamAvatars/edem.webp",
  //   team: "Tech",
  //   tag: "Tech Member",
  //   links: ["https://example.com/edem"],
  //   quote: "Placeholder quote",
  // },
  {
    firstName: "Aryan",
    lastName: "Dhawan",
    image: "/teamAvatars/aryan-dhawan.webp",
    team: "Tech",
    tag: "Tech Member",
    pronouns: "he/him",
    links: ["https://www.linkedin.com/in/aryan-dhawan"],
    quote: "Ideate fast, create fast, iterate fast.",
  },
  {
    firstName: "Wahib",
    lastName: "Barqawi",
    image: "/teamAvatars/wahib-barqawi.webp",
    team: "Tech",
    tag: "Tech Member",
    pronouns: "he/him",
    links: ["https://www.linkedin.com/in/wahib-barqawi"],
    quote: "No bug, no gain",
  },
  {
    firstName: "Sohel",
    lastName: "Shekh",
    // image: "/teamAvatars/sohel.webp",
    team: "Tech",
    tag: "Tech Member",
    pronouns: "he/him",
    links: ["https://sohel.tech"],
    quote: "Building cool things & finding the fun in the chaos",
  },

  // Design team
  {
    firstName: "Jess",
    lastName: "Zhang",
    image: "/teamAvatars/jess.webp",
    team: "Design",
    tag: "Design Lead",
    pronouns: "they/them",
    links: [
      "https://www.instagram.com/x.yuan.__/profilecard/?igsh=MXY0NnE1dWtiZXVxcw==",
    ],
    quote: ":3",
  },
  {
    firstName: "Julia",
    lastName: "Wu",
    image: "/teamAvatars/julia-wu.webp",
    team: "Design",
    tag: "Design Member",
    pronouns: "she/her",
    links: ["https://www.linkedin.com/in/julia-wu-413391319/"],
    quote: "art kid™",
  },
  {
    firstName: "Tina",
    lastName: "Zhang",
    // image: "/teamAvatars/tina.webp",
    team: "Design",
    tag: "Design Member",
    pronouns: "she/her",
    links: ["https://instagram.com/redonionn2"],
    quote: "Yippee!",
  },

  // Outreach team
  {
    firstName: "Nirek",
    lastName: "Shetty",
    // image: "/teamAvatars/nirek.webp",
    team: "Outreach",
    tag: "Outreach Lead",
    pronouns: "he/him",
    links: ["https://nirekshetty.com"],
    quote:
      "This is a rat race. But I'm no rat. I'm a f***ing turtle, ninja turtle. So which one is your favourite? I like Michelangelo.",
  },
  {
    firstName: "Jad",
    lastName: "Menkara",
    // image: "/teamAvatars/jad.webp",
    team: "Outreach",
    tag: "Outreach Lead",
    pronouns: "he/him",
    links: ["https://www.linkedin.com/in/jad-menkara-1593942aa/"],
    quote:
      "Why don't skeletons fight each other? Because they don't have the guts!",
  },
  {
    firstName: "Ray",
    lastName: "Tan",
    // image: "/teamAvatars/greg.webp",
    team: "Outreach",
    tag: "Outreach Officer",
    links: ["https://www.linkedin.com/in/ray-tan-054ab4228/"],
    quote: "I am Ray Tan of Canada",
  },
  {
    firstName: "Tom",
    // image: "/teamAvatars/uday-khanna.webp",
    team: "Outreach",
    tag: "Outreach Member",
    links: ["https://example.com/tom"],
    quote: "Placeholder quote",
  },

  // Finance team
  {
    firstName: "Uday",
    lastName: "Khanna",
    // image: "/teamAvatars/uday.webp",
    team: "Finance",
    tag: "Finance Lead",
    links: ["https://www.linkedin.com/in/udaykhanna25/"],
    quote: '"There is No Tomorrow!" - Apollo Creed (Rocky III)',
  },
  // {
  //   firstName: "Derek",
  //   // image: "/teamAvatars/derek.webp",
  //   team: "Finance",
  //   tag: "Finance Member",
  //   links: ["https://example.com/derek"],
  //   quote: "Placeholder quote",
  // },
  // {
  //   firstName: "Shayaan",
  //   // image: "/teamAvatars/shayaan.webp",
  //   team: "Finance",
  //   tag: "Finance Member",
  //   links: ["https://example.com/shayaan"],
  //   quote: "Placeholder quote",
  // },
  {
    firstName: "Sardul",
    lastName: "Subedi",
    // image: "/teamAvatars/sardaul.webp",
    team: "Finance",
    tag: "Finance Member",
    pronouns: "he/him",
    links: ["https://www.linkedin.com/in/sardul-subedi-63a838290/"],
    quote: "meh, close enough - Mediocrates",
  },

  // Logistics team
  {
    firstName: "Aayan",
    lastName: "Rahman",
    image: "/teamAvatars/aayan-rahman.webp",
    team: "Logistics",
    tag: "Logistics Lead",
    pronouns: "he/him",
    links: ["https://www.linkedin.com/in/aayan-rahman/"],
    quote:
      "I don't write code, but I make sure the hackers are fueled to write theirs.",
  },
  {
    firstName: "Emilo",
    // image: "/teamAvatars/emilo.webp",
    team: "Logistics",
    tag: "Logistics Lead",
    links: ["https://example.com/emilo"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Jia",
    lastName: "Peng",
    image: "/teamAvatars/jia.webp",
    team: "Logistics",
    tag: "Logistics Member",
    links: ["https://www.instagram.com/itsacedar_/"],
    quote: "child consumer (on wednesdays)",
  },
  {
    firstName: "Yang",
    // image: "/teamAvatars/yang.webp",
    team: "Logistics",
    tag: "Logistics Lead",
    links: ["https://yangxue.ca"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Arnnav",
    image: "/teamAvatars/arnnav-kudale.webp",
    team: "Logistics",
    tag: "Logistics Member",
    links: [],
    quote: "Placeholder quote",
  },
  {
    firstName: "Advaith",
    // image: "/teamAvatars/advaith.webp",
    team: "Logistics",
    tag: "Logistics Member",
    links: ["https://example.com/advaith"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Edward",
    image: "/teamAvatars/edward.webp",
    team: "Logistics",
    tag: "Logistics Executive",
    links: ["https://www.linkedin.com/in/edward-drobnis"],
    quote: "Placeholder quote",
  },

  // Marketing team
  {
    firstName: "Chelsea",
    lastName: "Wong",
    image: "/teamAvatars/chelsea-w.webp",
    team: "Marketing",
    tag: "Head of Marketing",
    pronouns: "she/her",
    links: ["https://www.linkedin.com/in/chelseawong07/"],
    quote: "stan enhypen",
  },
  {
    firstName: "Ev",
    image: "/teamAvatars/ev-wong.webp",
    team: "Marketing",
    tag: "Marketing Lead",
    links: ["https://www.evelynw.ong"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Yashas",
    // image: "/teamAvatars/yashas.webp",
    team: "Marketing",
    tag: "Marketing Lead",
    links: ["https://example.com/yashas"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Naman",
    image: "/teamAvatars/sycora.webp",
    team: "Marketing",
    tag: "Marketing Member",
    links: ["https://namansonawane.vercel.app/"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Anushka",
    image: "/teamAvatars/anushka-kshirsagar.webp",
    team: "Marketing",
    tag: "Marketing Member",
    links: ["https://www.linkedin.com/in/anushka-kshirsagar211/"],
    quote: "Placeholder quote",
  },
  {
    firstName: "Claire",
    lastName: "Lee",
    team: "Marketing",
    tag: "Animator",
    links: ["https://youtu.be/xvFZjo5PgG0?si=HaX9zZHYIwuW-h6e"],
    quote: "Placeholder quote",
  },
];
