import type { TeamMember } from "@/types/teams";

export const teamMembers: TeamMember[] = [
  // Admin team
  {
    id: 1,
    firstName: "William",
    lastName: "Wang",
    team: "Admin",
    tag: "Founder",
    pronouns: "",
    link: "https://www.linkedin.com/in/williamuw/",
    quote: "55x hackathon winner, karaoke enthusiast!",
  },
  {
    id: 2,
    firstName: "James",
    team: "Admin",
    tag: "Admin Member",
    link: "https://example.com/james",
    quote: "Placeholder quote",
  },
  {
    id: 3,
    firstName: "Jerry",
    team: "Admin",
    tag: "Admin Member",
    link: "https://example.com/jerry",
    quote: "Placeholder quote",
  },

  // Mentor team
  {
    id: 4,
    firstName: "Nausher",
    team: "Mentor",
    tag: "Mentor",
    link: "https://example.com/nausher",
    quote: "Placeholder quote",
  },
  {
    id: 5,
    firstName: "Arnnav",
    team: "Mentor",
    tag: "Mentor",
    link: "https://example.com/arnnav",
    quote: "Placeholder quote",
  },

  // Tech team
  {
    id: 6,
    firstName: "Jason",
    lastName: "Cameron",
    team: "Tech",
    tag: "Tech Lead",
    link: "https://www.linkedin.com/in/jsoncameron/",
    quote: "Sleep is for the week",
  },
  {
    id: 7,
    firstName: "Amol",
    team: "Tech",
    tag: "Tech Lead",
    link: "https://example.com/amol",
    quote: "Placeholder quote",
  },
  {
    id: 8,
    firstName: "Araf",
    lastName: "A Alam",
    team: "Tech",
    tag: "Project Manager",
    link: "https://www.linkedin.com/in/arafa821/",
    quote: "Code like crazy!",
  },
  {
    id: 9,
    firstName: "Chirag",
    pronouns: "he/him",
    image: "/teamAvatars/chirag.webp",
    team: "Tech",
    tag: "Senior Div Centerer",
    link: "https://github.com/ChiragDalmia/",
    quote: "I made this landing page ;)",
  },
  {
    id: 10,
    firstName: "Sohel",
    team: "Tech",
    tag: "Tech Member",
    link: "https://example.com/sohel",
    quote: "Placeholder quote",
  },
  {
    id: 11,
    firstName: "Aayan",
    team: "Tech",
    tag: "Tech Member",
    link: "https://example.com/aayan",
    quote: "Placeholder quote",
  },
  {
    id: 12,
    firstName: "Aiden",
    team: "Tech",
    tag: "Tech Member",
    link: "https://example.com/aiden",
    quote: "Placeholder quote",
  },
  {
    id: 13,
    firstName: "Joudat",
    team: "Tech",
    tag: "Tech Member",
    link: "https://example.com/joudat",
    quote: "Placeholder quote",
  },
  {
    id: 14,
    firstName: "James",
    team: "Tech",
    tag: "Tech Member",
    link: "https://example.com/james_l",
    quote: "Placeholder quote",
  },
  {
    id: 15,
    firstName: "Fiona",
    team: "Tech",
    tag: "Tech Member",
    link: "https://example.com/fiona",
    quote: "Placeholder quote",
  },
  {
    id: 16,
    firstName: "Edem",
    team: "Tech",
    tag: "Tech Member",
    link: "https://example.com/edem",
    quote: "Placeholder quote",
  },
  {
    id: 17,
    firstName: "Aryan",
    team: "Tech",
    tag: "Tech Member",
    link: "https://example.com/aryan",
    quote: "Placeholder quote",
  },
  {
    id: 18,
    firstName: "Wahib",
    team: "Tech",
    tag: "Tech Member",
    link: "https://example.com/wahib",
    quote: "Placeholder quote",
  },

  // Design team
  {
    id: 19,
    firstName: "Jess",
    team: "Design",
    tag: "Design Lead",
    link: "https://example.com/jess",
    quote: "Placeholder quote",
  },
  {
    id: 20,
    firstName: "Julia",
    team: "Design",
    tag: "Design Member",
    link: "https://example.com/julia",
    quote: "Placeholder quote",
  },
  {
    id: 21,
    firstName: "Tina",
    team: "Design",
    tag: "Design Member",
    link: "https://example.com/tina",
    quote: "Placeholder quote",
  },

  // Outreach team
  {
    id: 22,
    firstName: "Nirek",
    team: "Outreach",
    tag: "Outreach Lead",
    link: "https://example.com/nirek",
    quote: "Placeholder quote",
  },
  {
    id: 23,
    firstName: "Jad",
    team: "Outreach",
    tag: "Outreach Member",
    link: "https://example.com/jad",
    quote: "Placeholder quote",
  },
  {
    id: 24,
    firstName: "Greg",
    team: "Outreach",
    tag: "Outreach Member",
    link: "https://example.com/greg",
    quote: "Placeholder quote",
  },
  {
    id: 25,
    firstName: "Ray",
    lastName: "Tan",
    team: "Outreach",
    tag: "Outreach Officer",
    link: "https://www.linkedin.com/in/ray-tan-054ab4228/",
    quote: "I am Ray Tan of Canada",
  },
  {
    id: 26,
    firstName: "Tom",
    team: "Outreach",
    tag: "Outreach Member",
    link: "https://example.com/tom",
    quote: "Placeholder quote",
  },

  // Finance team
  {
    id: 27,
    firstName: "Uday",
    lastName: "Khanna",
    team: "Finance",
    tag: "Finance Lead",
    link: "https://www.linkedin.com/in/udaykhanna25/",
    quote: '"There is No Tomorrow!" - Apollo Creed (Rocky III)',
  },
  {
    id: 28,
    firstName: "Derek",
    team: "Finance",
    tag: "Finance Member",
    link: "https://example.com/derek",
    quote: "Placeholder quote",
  },
  {
    id: 29,
    firstName: "Shayaan",
    team: "Finance",
    tag: "Finance Member",
    link: "https://example.com/shayaan",
    quote: "Placeholder quote",
  },
  {
    id: 30,
    firstName: "Sardaul",
    team: "Finance",
    tag: "Finance Member",
    link: "https://example.com/sardaul",
    quote: "Placeholder quote",
  },

  // Logistics team
  {
    id: 31,
    firstName: "Aayan",
    team: "Logistics",
    tag: "Logistics Lead",
    link: "https://example.com/aayan_l",
    quote: "Placeholder quote",
  },
  {
    id: 32,
    firstName: "Emilo",
    team: "Logistics",
    tag: "Logistics Lead",
    link: "https://example.com/emilo",
    quote: "Placeholder quote",
  },
  {
    id: 33,
    firstName: "Jia",
    team: "Logistics",
    tag: "Logistics Member",
    link: "https://example.com/jia",
    quote: "Placeholder quote",
  },
  {
    id: 34,
    firstName: "Yang",
    team: "Logistics",
    tag: "Logistics Member",
    link: "https://example.com/yang",
    quote: "Placeholder quote",
  },
  {
    id: 35,
    firstName: "Arnav",
    team: "Logistics",
    tag: "Logistics Member",
    link: "https://example.com/arnav",
    quote: "Placeholder quote",
  },
  {
    id: 36,
    firstName: "Advaith",
    team: "Logistics",
    tag: "Logistics Member",
    link: "https://example.com/advaith",
    quote: "Placeholder quote",
  },
  {
    id: 37,
    firstName: "Edward",
    team: "Logistics",
    tag: "Logistics Member",
    link: "https://example.com/edward",
    quote: "Placeholder quote",
  },

  // Marketing team
  {
    id: 38,
    firstName: "Chelsea",
    lastName: "Wong",
    team: "Marketing",
    tag: "Head of Marketing",
    pronouns: "she/her",
    link: "https://www.linkedin.com/in/chelseawong07/",
    quote: "stan enhypen",
  },
  {
    id: 39,
    firstName: "Ev",
    team: "Marketing",
    tag: "Marketing Lead",
    link: "https://example.com/ev",
    quote: "Placeholder quote",
  },
  {
    id: 40,
    firstName: "Yashas",
    team: "Marketing",
    tag: "Marketing Lead",
    link: "https://example.com/yashas",
    quote: "Placeholder quote",
  },
  {
    id: 41,
    firstName: "Naman",
    team: "Marketing",
    tag: "Marketing Member",
    link: "https://example.com/naman",
    quote: "Placeholder quote",
  },
  {
    id: 42,
    firstName: "Anushka",
    team: "Marketing",
    tag: "Marketing Member",
    link: "https://example.com/anushka",
    quote: "Placeholder quote",
  },
  {
    id: 43,
    firstName: "Claire",
    lastName: "L",
    team: "Marketing",
    tag: "Marketing Member",
    link: "https://example.com/claire",
    quote: "Placeholder quote",
  },
];
