/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 can1.gltf --types 
Author: Julie.voets (https://sketchfab.com/Julie.voets)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/fanta-can-693bf5f618904a1aac1ffc93af4de8a4
Title: Fanta can
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Can_geo_Metal_subst_0: THREE.Mesh;
    Can_geo_Coke_logo_subst_0: THREE.Mesh;
  };
  materials: {
    Metal_subst: THREE.MeshStandardMaterial;
    Coke_logo_subst: THREE.MeshStandardMaterial;
  };
};

export default function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/can1.gltf") as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh
          geometry={nodes.Can_geo_Metal_subst_0.geometry}
          material={materials.Metal_subst}
        />
        <mesh
          geometry={nodes.Can_geo_Coke_logo_subst_0.geometry}
          material={materials.Coke_logo_subst}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/can1.gltf");
